name: Run Tests
on:
  push:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Print working directory
        run: pwd
      - name: Install dependencies
        run: python -m pip install --upgrade pip
      - name: Install pytest
        run: pip install pytest
      - name: Install bibtexparser
        run: python -m pip install bibtexparser
      - name: Install requests
        run: python -m pip install requests
      - name: Run pytest
        run: pytest
      - name: Install Black
        run: pip install black
      - name: Install pylint
        run: pip install pylint
      - name: Run Black
        run: black 
      - name: Run pylint
        run: pylint 
 
